name: Flutter iOS CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BASE64_CERTIFICATE_DISTRIBUTION }}
          DEV_CERT_BASE64: ${{ secrets.BASE64_CERTIFICATE_DEVELOPER }}
          P12_PASSWORD: ${{ secrets.PASSWORD_CERTIFICATE_DISTRIBUTION }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BASE64_PP_CICDTESTAPP }}
          KEYCHAIN_PASSWORD: ${{ secrets.PASSWORD_KEYCHAIN }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/dis_build_certificate.p12
          DEV_CERTIFICATE_PATH=$RUNNER_TEMP/dev_build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$DEV_CERT_BASE64" | base64 --decode -o $DEV_CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          ls -l $RUNNER_TEMP

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lt 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $DEV_CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
        
      - name: Export Archive
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     archive \
                     -archivePath $PWD/build/Runner.xcarchive \
                     DEVELOPMENT_TEAM="LQ6RFS97ZY" \
                     -allowProvisioningUpdates


      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/Runner.xcarchive \
                     -exportOptionsPlist ios/Runner/ExportOptions.plist \
                     -exportPath $PWD/build/ios_release
    

    # - name: Create iOS appbundle release
    #   env:
    #     KEYCHAIN_PASSWORD: ${{ secrets.PASSWORD_KEYCHAIN }}
    #   run: |
    #     security unlock-keychain -p "$PASSWORD_KEYCHAIN" $RUNNER_TEMP/app-signing.keychain-db
    #     flutter build ipa \
    #       --release \
    #       --export-options-plist="${{ github.workspace }}/ios/Runner/ExportOptions.plist"

    # - name: Deploy to App Store (Testflight)
    #   uses: apple-actions/upload-testflight-build@v1
    #   with:
    #     app-path: ${{ github.workspace }}/build/ios/archive/ipa/ci_cd_flutter_demo_ios_app.ipa
    #     issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
    #     api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
    #     api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: ios-release
    #     path: build/ios/archive/ipa
